# Generated by Django 4.1.5 on 2023-01-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('tgUserName', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.user')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.topic')),
            ],
        ),
    ]
